{
 "title": "ROCm GPU Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "Device ID",
    "query": {
     "query": "label_values(rocm_smi_edge_temperature,device_id)"
    }
   },
   {
    "name": "device_name",
    "label": "Device Name",
    "query": {
     "query": "label_values(rocm_smi_edge_temperature,device_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Real-time Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Edge Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocm_smi_edge_temperature{device_id=\"$device_id\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocm_smi_socket_power{device_id=\"$device_id\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocm_smi_gpu_usage{device_id=\"$device_id\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRAM Allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocm_smi_gpu_vram_allocation{device_id=\"$device_id\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "Edge Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "rocm_smi_edge_temperature{device_id=\"$device_id\", device_name=\"$device_name\"}",
     "legendFormat": "Edge Temperature"
    }
   ]
  },
  {
   "title": "Socket Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rocm_smi_socket_power{device_id=\"$device_id\", device_name=\"$device_name\"}",
     "legendFormat": "Edge Temperature"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "rocm_smi_gpu_usage{device_id=\"$device_id\", device_name=\"$device_name\"}",
     "legendFormat": "Edge Temperature"
    }
   ]
  },
  {
   "title": "VRAM Allocation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "rocm_smi_gpu_vram_allocation{device_id=\"$device_id\", device_name=\"$device_name\"}",
     "legendFormat": "Edge Temperature"
    }
   ]
  }
 ]
}